# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LandChangeDetector
                                 A QGIS plugin
 detect land use/cover change.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-22
        copyright            : (C) 2025 by ayakari
        email                : ayakari1126@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'ayakari'
__date__ = '2025-06-22'
__copyright__ = '(C) 2025 by ayakari'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LandChangeDetector class from file LandChangeDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .land_change_detector import LandChangeDetectorPlugin
    return LandChangeDetectorPlugin()
